export const GET_INSTRUCTIONS = "GET_INSTRUCTIONS"
export const RESP_GET_INSTRUCTIONS = "RESP_GET_INSTRUCTIONS"

export const GET_GROUP_LIST_INST = "GET_GROUP_LIST_INST"
export const RESP_GET_GROUP_LIST_INST = "RESP_GET_GROUP_LIST_INST"

export const GET_ALL_STATUS = "GET_ALL_STATUS"
export const RESP_GET_ALL_STATUS = "RESP_GET_ALL_STATUS"

export const GET_MANAGER = "GET_MANAGER"
export const RESP_GET_MANAGER = "RESP_GET_MANAGER"

export const GET_OWNER = "GET_OWNER"
export const RESP_GET_OWNER = "RESP_GET_OWNER"

export const GET_SELECTED_MANAGER = "GET_SELECTED_MANAGER"
export const RESP_SELECTED_MANAGER = "RESP_SELECTED_MANAGER"

export const GET_STATUS = "GET_STATUS"
export const RESP_GET_STATUS = "RESP_GET_STATUS"

export const GET_INSTRUCTIONS2 = "GET_INSTRUCTIONS2"
export const RESP_GET_INSTRUCTIONS2 = "RESP_GET_INSTRUCTIONS2"
export const SAVE_INSTRUCTIONS = "SAVE_INSTRUCTIONS"
export const EDIT_INSTRUCTIONS = "EDIT_INSTRUCTIONS"
export const DELETE_INSTRUCTIONS = "DELETE_INSTRUCTIONS"
export const MSGADD = "MSGADD"
export const MSGEDIT = "MSGEDIT"
export const MSGDELETE = "MSGDELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"
// export const GET_USER_LIST = "GET_USER_LIST"
// export const RESP_GET_USER_LIST = "RESP_GET_USER_LIST"
export const GET_DETAIL_INSTRUCTION = "GET_DETAIL_INSTRUCTION"
export const RESP_GET_DETAIL_INSTRUCTION = "RESP_GET_DETAIL_INSTRUCTION"
export const SAVE_DESCRIPTION = "SAVE_DESCRIPTION"

export const GET_CHECK_DOWNLOAD = "GET_CHECK_DOWNLOAD"
export const RESP_GET_CHECK_DOWNLOAD = "RESP_GET_CHECK_DOWNLOAD"

export const DOWNLOAD_FILES = "DOWNLOAD_FILES"
export const MSGDOWNLOAD = "MSGDOWNLOAD"

/* Reply Instructions */

export const GET_REPLY = "GET_REPLY"
export const RESP_GET_REPLY = "RESP_GET_REPLY"

export const GET_SELECTED_REPLY = "GET_SELECTED_REPLY"
export const RESP_GET_SELECTED_REPLY = "RESP_GET_SELECTED_REPLY"

export const SAVE_REPLY = "SAVE_REPLY"

export const EDIT_REPLY = "EDIT_REPLY"

export const DELETE_REPLY = "DELETE_REPLY"

export const MSGADDREPLY = "MSGADDREPLY"
export const MSGEDITREPLY = "MSGEDITREPLY"
export const MSGDELETEREPLY = "MSGDELETEREPLY"

/* Attachment Instructions */

export const GET_ATTACHMENT = "GET_ATTACHMENT"
export const RESP_GET_ATTACHMENT = "RESP_GET_ATTACHMENT"

/* Logs Instructions */

export const GET_LOGS = "GET_LOGS"
export const RESP_GET_LOGS = "RESP_GET_LOGS"