/* GET ALL SETTING */
export const GET_SETTING = "GET_SETTING"
export const RESP_GET_SETTING = "RESP_GET_SETTING"

export const SAVE_MEMBERS = "SAVE_MEMBERS"
export const EDIT_MEMBERS = "EDIT_MEMBERS"
export const DELETE_MEMBERS = "DELETE_MEMBERS"
export const MSGADD = "MSGADD"
export const MSGEDIT = "MSGEDIT"
export const MSGDELETE = "MSGDELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"

//general setting
export const GET_GENERAL_SETTING = "GET_GENERAL_SETTING"
export const RESP_GET_GENERAL_SETTING = "RESP_GET_GENERAL_SETTING"
export const EDIT_GENERAL_SETTING = "EDIT_GENERAL_SETTING"

//members
export const GET_MEMBERS = "GET_MEMBERS"
export const RESP_GET_MEMBERS = "RESP_GET_MEMBERS"

export const GET_MEMBERS2 = "GET_MEMBERS2"
export const RESP_GET_MEMBERS2 = "RESP_GET_MEMBERS2"

//rank list
export const GET_RANK_LIST = "GET_RANK_LIST"
export const RESP_GET_RANK_LIST = "RESP_GET_RANK_LIST"

//permission list
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST"
export const RESP_GET_PERMISSION_LIST = "RESP_GET_PERMISSION_LIST"

//group list
export const GET_GROUP_LIST = "GET_GROUP_LIST"
export const RESP_GET_GROUP_LIST = "RESP_GET_GROUP_LIST"

//group list
export const GET_RELATION_LIST = "GET_RELATION_LIST"
export const RESP_GET_RELATION_LIST = "RESP_GET_RELATION_LIST"

export const SAVE_GROUP_MAPPING = "SAVE_GROUP_MAPPING"
export const EDIT_GROUP_MAPPING = "EDIT_GROUP_MAPPING"
export const DELETE_GROUP_MAPPING = "DELETE_GROUP_MAPPING"
export const MSGADDGROUPMAP = "MSGADDGROUPMAP"
export const MSGEDITGROUPMAP = "MSGEDITGROUPMAP"
export const MSGDELETEGROUPMAP = "MSGDELETEGROUPMAP"

export const GET_MEMBERS_MAPPING = "GET_MEMBERS_MAPPING"
export const RESP_GET_MEMBERS_MAPPING = "RESP_GET_MEMBERS_MAPPING"

export const GET_LIST_MENU = "GET_LIST_MENU"
export const RESP_GET_MENU_LIST = "RESP_GET_MENU_LIST"

export const GET_MENU2 = "GET_MENU2"
export const RESP_GET_MENU2 = "RESP_GET_MENU2"

export const SAVE_MENU = "SAVE_MENU"
export const EDIT_MENU = "EDIT_MENU"
export const DELETE_MENU = "DELETE_MENU"