/* GET ALL SETTING */
export const GET_SETTING = "GET_SETTING"
export const RESP_GET_SETTING = "RESP_GET_SETTING"

export const SAVE_MEMBERS = "SAVE_MEMBERS"
export const EDIT_MEMBERS = "EDIT_MEMBERS"
export const DELETE_MEMBERS = "DELETE_MEMBERS"
export const MSGADD = "MSGADD"
export const MSGEDIT = "MSGEDIT"
export const MSGDELETE = "MSGDELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"

//general setting
export const GET_GENERAL_SETTING = "GET_GENERAL_SETTING"
export const RESP_GET_GENERAL_SETTING = "RESP_GET_GENERAL_SETTING"
export const EDIT_GENERAL_SETTING = "EDIT_GENERAL_SETTING"