/* GET ALL SETTING */
export const GET_SETTING = "GET_SETTING"
export const RESP_GET_SETTING = "RESP_GET_SETTING"

export const SAVE_MEMBERS = "SAVE_MEMBERS"
export const EDIT_MEMBERS = "EDIT_MEMBERS"
export const DELETE_MEMBERS = "DELETE_MEMBERS"
export const MSGADD = "MSGADD"
export const MSGEDIT = "MSGEDIT"
export const MSGDELETE = "MSGDELETE"
export const RESET_MESSAGE = "RESET_MESSAGE"

//general setting
export const GET_GENERAL_SETTING = "GET_GENERAL_SETTING"
export const RESP_GET_GENERAL_SETTING = "RESP_GET_GENERAL_SETTING"
export const EDIT_GENERAL_SETTING = "EDIT_GENERAL_SETTING"

//members
export const GET_MEMBERS = "GET_MEMBERS"
export const RESP_GET_MEMBERS = "RESP_GET_MEMBERS"

export const GET_MEMBERS2 = "GET_MEMBERS2"
export const RESP_GET_MEMBERS2 = "RESP_GET_MEMBERS2"

//rank list
export const GET_RANK_LIST = "GET_RANK_LIST"
export const RESP_GET_RANK_LIST = "RESP_GET_RANK_LIST"

//permission list
export const GET_PERMISSION_LIST = "GET_PERMISSION_LIST"
export const RESP_GET_PERMISSION_LIST = "RESP_GET_PERMISSION_LIST"

//group list
export const GET_GROUP_LIST = "GET_GROUP_LIST"
export const RESP_GET_GROUP_LIST = "RESP_GET_GROUP_LIST"

//group list
export const GET_RELATION_LIST = "GET_RELATION_LIST"
export const RESP_GET_RELATION_LIST = "RESP_GET_RELATION_LIST"

export const SAVE_GROUP_MAPPING = "SAVE_GROUP_MAPPING"
export const EDIT_GROUP_MAPPING = "EDIT_GROUP_MAPPING"
export const DELETE_GROUP_MAPPING = "DELETE_GROUP_MAPPING"
export const MSGADDGROUPMAP = "MSGADDGROUPMAP"
export const MSGEDITGROUPMAP = "MSGEDITGROUPMAP"
export const MSGDELETEGROUPMAP = "MSGDELETEGROUPMAP"

export const GET_MEMBERS_MAPPING = "GET_MEMBERS_MAPPING"
export const RESP_GET_MEMBERS_MAPPING = "RESP_GET_MEMBERS_MAPPING"

//menu

export const GET_LIST_MENU = "GET_LIST_MENU"
export const RESP_GET_MENU_LIST = "RESP_GET_MENU_LIST"

export const GET_MENU2 = "GET_MENU2"
export const RESP_GET_MENU2 = "RESP_GET_MENU2"

export const SAVE_MENU = "SAVE_MENU"
export const EDIT_MENU = "EDIT_MENU"
export const DELETE_MENU = "DELETE_MENU"

// Role Setting
export const GET_ROLE_LIST = "GET_ROLE_LIST"
export const RESP_GET_ROLE_LIST = "RESP_GET_ROLE_LIST"

export const GET_ROLE = "GET_ROLE"
export const RESP_GET_ROLE = "RESP_GET_ROLE"

export const GET_ROLE_ACCESS = "GET_ROLE_ACCESS"
export const RESP_GET_ROLE_ACCESS = "RESP_GET_ROLE_ACCESS"

export const GET_ROLE_ACCESS_LIST = "GET_ROLE_ACCESS_LIST"
export const RESP_GET_ROLE_ACCESS_LIST = "RESP_GET_ROLE_ACCESS_LIST"
export const SAVE_ACCESS_ROLE = "SAVE_ACCESS_ROLE"
export const EDIT_ACCESS_ROLE = "EDIT_ACCESS_ROLE"
export const DELETE_ACCESS_ROLE = "DELETE_ACCESS_ROLE"

export const SAVE_ROLE = "SAVE_ROLE"
export const EDIT_ROLE = "EDIT_ROLE"
export const DELETE_ROLE = "DELETE_ROLE"

export const GET_GROUP_LIST_ROLE_ACCESS = "GET_GROUP_LIST_ROLE_ACCESS"
export const RESP_GET_GROUP_LIST_ROLE_ACCESS = "RESP_GET_GROUP_LIST_ROLE_ACCESS"

//lang
export const GET_LANGUAGE_LIST = "GET_LANGUAGE_LIST"
export const RESP_GET_LANGUAGE_LIST = "RESP_GET_LANGUAGE_LIST"

//kpi category

export const GET_KPI_CATEGORY_LIST = "GET_KPI_CATEGORY_LIST"
export const RESP_GET_KPI_CATEGORY_LIST = "RESP_GET_KPI_CATEGORY_LIST"

export const GET_KPI_CATEGORY = "GET_KPI_CATEGORY"
export const RESP_GET_KPI_CATEGORY = "RESP_GET_KPI_CATEGORY"

export const SAVE_KPI_CATEGORY = "SAVE_KPI_CATEGORY"
export const EDIT_KPI_CATEGORY = "EDIT_KPI_CATEGORY"
export const DELETE_KPI_CATEGORY = "DELETE_KPI_CATEGORY"

//kpi unit

export const GET_KPI_UNIT_LIST = "GET_KPI_UNIT_LIST"
export const RESP_GET_KPI_UNIT_LIST = "RESP_GET_KPI_UNIT_LIST"

export const GET_KPI_UNIT = "GET_KPI_UNIT"
export const RESP_GET_KPI_UNIT = "RESP_GET_KPI_UNIT"

export const SAVE_KPI_UNIT = "SAVE_KPI_UNIT"
export const EDIT_KPI_UNIT = "EDIT_KPI_UNIT"
export const DELETE_KPI_UNIT = "DELETE_KPI_UNIT"

//kpi item

export const GET_KPI_ITEM_LIST = "GET_KPI_ITEM_LIST"
export const RESP_GET_KPI_ITEM_LIST = "RESP_GET_KPI_ITEM_LIST"

export const GET_KPI_ITEM = "GET_KPI_ITEM"
export const RESP_GET_KPI_ITEM = "RESP_GET_KPI_ITEM"

export const SAVE_KPI_ITEM = "SAVE_KPI_ITEM"
export const EDIT_KPI_ITEM = "EDIT_KPI_ITEM"
export const DELETE_KPI_ITEM = "DELETE_KPI_ITEM"