export const GET_YEAR_LIST = "GET_YEAR_LIST"
export const RESP_GET_YEAR_LIST = "RESP_GET_YEAR_LIST"

export const GET_GROUP_LIST_KPI = "GET_GROUP_LIST_KPI"
export const RESP_GET_GROUP_LIST_KPI = "RESP_GET_GROUP_LIST_KPI"

export const GET_CORPORATION_LIST = "GET_CORPORATION_LIST"
export const RESP_GET_CORPORATION_LIST = "RESP_GET_CORPORATION_LIST"

export const GET_COLUMN_LIST = "GET_COLUMN_LIST"
export const RESP_GET_COLUMN_LIST = "RESP_GET_COLUMN_LIST"

export const GET_KPI_MASTER = "GET_KPI_MASTER"
export const RESP_GET_KPI_MASTER = "RESP_GET_KPI_MASTER"

export const GET_PLAN = "GET_PLAN"
export const RESP_GET_PLAN = "RESP_GET_PLAN"

export const GET_ITEM_LIST = "GET_ITEM_LIST"
export const RESP_GET_ITEM_LIST = "RESP_GET_ITEM_LIST"

export const GET_UNIT_LIST = "GET_UNIT_LIST"
export const RESP_GET_UNIT_LIST = "RESP_GET_UNIT_LIST"

export const GET_DASHBOARD_KPI = "GET_DASHBOARD_KPI"
export const RESP_GET_DASHBOARD_KPI = "RESP_GET_DASHBOARD_KPI"

export const GET_ACTUAL_INPUT_DATA = "GET_ACTUAL_INPUT_DATA"
export const RESP_GET_ACTUAL_INPUT_DATA = "RESP_GET_ACTUAL_INPUT_DATA"

export const DOWNLOAD_MASTER_TEMPLATE = "DOWNLOAD_MASTER_TEMPLATE"
export const DOWNLOAD_PLAN_TEMPLATE = "DOWNLOAD_PLAN_TEMPLATE"

export const RESET_MESSAGE = "RESET_MESSAGE"

export const UPLOAD_MASTER_KPI = "UPLOAD_MASTER_KPI"
export const UPLOAD_PLAN_KPI = "UPLOAD_PLAN_KPI"
export const MSG_UPLOAD = "MSG_UPLOAD"

// export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE"
// export const MSGEDIT = "MSGEDIT"