export const GET_GROUP_LIST_KPI = "GET_GROUP_LIST_KPI"
export const RESP_GET_GROUP_LIST_KPI = "RESP_GET_GROUP_LIST_KPI"

export const GET_GROUP_LIST_KPI_INPUT = "GET_GROUP_LIST_KPI_INPUT"
export const RESP_GET_GROUP_LIST_KPI_INPUT = "RESP_GET_GROUP_LIST_KPI_INPUT"

export const GET_CORPORATION_LIST = "GET_CORPORATION_LIST"
export const RESP_GET_CORPORATION_LIST = "RESP_GET_CORPORATION_LIST"

export const GET_KPI_ITEM_LIST = "GET_KPI_ITEM_LIST"
export const RESP_GET_KPI_ITEM_LIST = "RESP_GET_KPI_ITEM_LIST"

export const GET_KPI_MASTER = "GET_KPI_MASTER"
export const RESP_GET_KPI_MASTER = "RESP_GET_KPI_MASTER"

export const GET_ITEM_LIST = "GET_ITEM_LIST"
export const RESP_GET_ITEM_LIST = "RESP_GET_ITEM_LIST"

export const GET_UNIT_LIST = "GET_UNIT_LIST"
export const RESP_GET_UNIT_LIST = "RESP_GET_UNIT_LIST"

export const GET_DASHBOARD_KPI = "GET_DASHBOARD_KPI"
export const RESP_GET_DASHBOARD_KPI = "RESP_GET_DASHBOARD_KPI"

export const GET_DASHBOARD_DETAIL_KPI = "GET_DASHBOARD_DETAIL_KPI"
export const RESP_GET_DASHBOARD_DETAIL_KPI = "RESP_GET_DASHBOARD_DETAIL_KPI"

export const GET_KPI_INPUT_DATA = "GET_ACTUAL_INPUT_DATA"
export const RESP_GET_KPI_INPUT_DATA = "RESP_GET_ACTUAL_INPUT_DATA"

export const GET_KPI_FILE = "GET_KPI_FILE"
export const RESP_GET_KPI_FILE = "RESP_GET_KPI_FILE"

export const DOWNLOAD_KPI_TEMPLATE = "DOWNLOAD_KPI_TEMPLATE"
export const DOWNLOAD_DASHBOARD_DETAIL = "DOWNLOAD_DASHBOARD_DETAIL"
export const DOWNLOAD_KPI_EXCEL = "DOWNLOAD_KPI_EXCEL"

export const RESET_MESSAGE = "RESET_MESSAGE"

export const UPLOAD_KPI = "UPLOAD_KPI"
export const UPLOAD_KPI_RESULT = "UPLOAD_KPI_RESULT"
export const MSG_UPLOAD = "MSG_UPLOAD"

export const SET_KPI_NOTE = "SET_KPI_NOTE"
export const SET_KPI_NOTE_TO_DELETE = "SET_KPI_NOTE_TO_DELETE"

export const MSG_EDIT = "MSG_EDIT"
export const MSG_DELETE = "MSG_DELETE"