export const GET_YEAR_LIST = "GET_YEAR_LIST"
export const RESP_GET_YEAR_LIST = "RESP_GET_YEAR_LIST"

export const GET_GROUP_LIST_KPI = "GET_GROUP_LIST_KPI"
export const RESP_GET_GROUP_LIST_KPI = "RESP_GET_GROUP_LIST_KPI"

export const GET_COORPORATION_LIST = "GET_COORPORATION_LIST"
export const RESP_GET_COORPORATION_LIST = "RESP_GET_COORPORATION_LIST"

export const GET_PLAN = "GET_PLAN"
export const RESP_GET_PLAN = "RESP_GET_PLAN"

export const RESET_MESSAGE = "RESET_MESSAGE"

// export const EDIT_USER_PROFILE = "EDIT_USER_PROFILE"
// export const MSGEDIT = "MSGEDIT"