export const LOV_MENU_PARENT = "LOV_MENU_PARENT"
export const LOV_USER = "LOV_USER"
export const LOV_DIV = "LOV_DIV"
export const MSG_LOV = "MSG_LOV"
export const LOV_ROLE = "MSG_LOV"
export const LOV_MENU = "LOV_MENU"
export const LOV_COMPANY = "LOV_COMPANY"