export const GET_GROUP_LIST = "GET_GROUP_LIST"
export const RESP_GET_GROUP_LIST = "RESP_GET_GROUP_LIST"

export const GET_COMPANY_LIST = "GET_COMPANY_LIST"
export const RESP_GET_COMPANY_LIST = "RESP_GET_COMPANY_LIST"

export const GET_MOVING_PLAN_DASHBOARD_LIST = "GET_MOVING_PLAN_DASHBOARD_LIST"
export const RESP_GET_MOVING_PLAN_DASHBOARD_LIST = "RESP_GET_MOVING_PLAN_DASHBOARD_LIST"

export const GET_MOVING_PLAN_INPUT_RESULT_LIST = "GET_MOVING_PLAN_INPUT_RESULT_LIST"
export const RESP_GET_MOVING_PLAN_INPUT_RESULT_LIST = "RESP_GET_MOVING_PLAN_INPUT_RESULT_LIST"

export const DOWNLOAD_MOVING_PLAN_DASHBOARD_EXCEL = "DOWNLOAD_MOVING_PLAN_DASHBOARD_EXCEL"

export const RESET_MESSAGE = "RESET_MESSAGE"