export const GET_COMPANY_CODE_LIST = "GET_COMPANY_CODE_LIST"
export const RESP_GET_COMPANY_CODE_LIST = "RESP_GET_COMPANY_CODE_LIST"

export const GET_MOVING_PLAN_LIST = "GET_MOVING_PLAN_LIST"
export const RESP_GET_MOVING_PLAN_LIST = "RESP_GET_MOVING_PLAN_LIST"

export const DOWNLOAD_MOVING_PLAN = "DOWNLOAD_MOVING_PLAN"

export const RESET_MESSAGE = "RESET_MESSAGE"