
export const GET_COMBO = "GET_COMBO"
export const MSG_COMBO_GYS_AREA_TYPE = "MSG_COMBO_GYS_AREA_TYPE"
export const MSG_COMBO_ROLE_AKSES_TYPE = "MSG_COMBO_ROLE_AKSES_TYPE"
export const MSG_COMBO_SATUAN = "MSG_COMBO_SATUAN"
export const MSG_COMBO_SATUAN_MATERIAL = "MSG_COMBO_SATUAN_MATERIAL"
export const MSG_COMBO_TYPE = "MSG_COMBO_TYPE"
export const MSG_COMBO_JENIS_APPROVAL = "MSG_COMBO_JENIS_APPROVAL"